"
" Nicolas Dufour's Vimrc
"

" Sets how many lines of history VIM has to remember
set history=500

" Enable filetype plugins
filetype plugin on
filetype indent on

" Set to auto read when a file is changed from the outside
set autoread

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

" Fast saving
nmap <leader>w :w!<cr>

" Turn on the WiLd menu
set wildmenu

" General settings
set backspace=indent,eol,start "Allow backspace in insert mode
set encoding=utf-8
set title
set autoindent

" Make sure you use tabs and display them as 4 spaces
set shiftwidth=0
set softtabstop=0
set tabstop=4

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Scroll 7 lines
set so=7

" =============== UI ================
" Syntax highlighting
syntax on

set ruler
set number    " Display line number
set numberwidth=5
set showmatch " Show matching brackets when text indicator is over them
set showmode  " Display the current mode
set hlsearch  " Highlight search results

" Display extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

" Use one space, not two, after punctuation.
set nojoinspaces

" Make it obvious where 80 characters is -- Disabled
" set textwidth=80
" set colorcolumn=+1

" Don't redraw while executing macros (good performance config)
set lazyredraw

set bg=dark
set laststatus=2
highlight StatusLine ctermfg=blue ctermbg=white  " Highlight the status line

" ================ Turn Off Swap Files ==============
" Turn off backup files
set noswapfile
set nobackup
set nowb

" Misc
" Press F3 to turn on/off the automatic indent when pasting
set pastetoggle=<F3>

